"""Add summary fields to article model

Revision ID: 5f0ba8c5a96c
Revises: dbe0291b88ab
Create Date: 2025-08-12 21:14:37.198898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0ba8c5a96c'
down_revision: Union[str, Sequence[str], None] = 'dbe0291b88ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('extractive_summary', sa.Text(), nullable=True, comment='Extractive summary of the article content'))
    op.add_column('articles', sa.Column('beginner_summary', sa.Text(), nullable=True, comment='Beginner-friendly summary with simplified language'))
    op.add_column('articles', sa.Column('technical_summary', sa.Text(), nullable=True, comment='Technical summary preserving specialized terminology'))
    op.add_column('articles', sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True, comment='When the summaries were generated'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'summary_generated_at')
    op.drop_column('articles', 'technical_summary')
    op.drop_column('articles', 'beginner_summary')
    op.drop_column('articles', 'extractive_summary')
    # ### end Alembic commands ###
