"""Add sentiment analysis fields to article model

Revision ID: c5412687955f
Revises: e1313bc9e7b1
Create Date: 2025-08-10 22:16:07.409813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5412687955f'
down_revision: Union[str, Sequence[str], None] = 'e1313bc9e7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('sentiment_label', sa.String(length=20), nullable=True, comment='Sentiment label (positive, negative, neutral)'))
    op.add_column('articles', sa.Column('sentiment_confidence', sa.Float(), nullable=True, comment='Confidence score for sentiment analysis (0-1)'))
    op.alter_column('articles', 'sentiment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Sentiment score from -1 (negative) to 1 (positive)',
               existing_nullable=True)
    op.create_index(op.f('ix_articles_sentiment_score'), 'articles', ['sentiment_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_sentiment_score'), table_name='articles')
    op.alter_column('articles', 'sentiment_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Sentiment score from -1 (negative) to 1 (positive)',
               existing_nullable=True)
    op.drop_column('articles', 'sentiment_confidence')
    op.drop_column('articles', 'sentiment_label')
    # ### end Alembic commands ###
