"""Add sensationalism fields to article model

Revision ID: dbe0291b88ab
Revises: c5412687955f
Create Date: 2025-08-11 20:55:38.086578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe0291b88ab'
down_revision: Union[str, Sequence[str], None] = 'c5412687955f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('political_bias_score', sa.Float(), nullable=True, comment='Political bias score from -1.0 (far left) to 1.0 (far right)'))
    op.add_column('articles', sa.Column('political_bias_label', sa.String(length=50), nullable=True, comment='Political bias'))
    op.add_column('articles', sa.Column('sensationalism_score', sa.Float(), nullable=True, comment='Sensationalism score from 0.0 (objective) to 1.0 (sensationalist)'))
    op.add_column('articles', sa.Column('sensationalism_label', sa.String(length=20), nullable=True, comment='Sensationalism label (factual, somewhat sensational, highly sensational)'))
    op.create_index(op.f('ix_articles_sensationalism_score'), 'articles', ['sensationalism_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_sensationalism_score'), table_name='articles')
    op.drop_column('articles', 'sensationalism_label')
    op.drop_column('articles', 'sensationalism_score')
    op.drop_column('articles', 'political_bias_label')
    op.drop_column('articles', 'political_bias_score')
    # ### end Alembic commands ###
